---
driver:
  name: vagrant
  customize:
    memory: 2048
    cpus: 2
    ioapic: 'on'

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
    run_list:
      - recipe[apt]
    attributes:
      java:
        jdk_version: 7

suites:
  - name: mesosphere_slave
    run_list:
      # master recipe is only for asserting mesos-slave healthy startup.
      - recipe[mesos::master]
      - recipe[mesos::slave]
    attributes:
      mesos:
        type: mesosphere
        slave:
          master: 'zk://localhost:2181/mesos'
        # these keys below are only for master configurations.
        master_ips: ['10.0.0.1', '10.0.0.2', '10.0.0.3']
        slave_ips:  ['11.0.0.1', '11.0.0.2', '11.0.0.3']
        mesosphere:
          with_zookeeper: true
  - name: mesosphere_master
    run_list:
      - recipe[mesos::master]
    attributes:
      mesos:
        type: mesosphere
        mesosphere:
          with_zookeeper: true
        master:
          zk: 'zk://localhost:2181/mesos'
        master_ips: ['10.0.0.1', '10.0.0.2', '10.0.0.3']
        slave_ips:  ['11.0.0.1', '11.0.0.2', '11.0.0.3']
  - name: source_master
    run_list:
      - recipe[mesos::master]
    attributes:
      mesos:
        type: source
        master_ips: ['10.0.0.1', '10.0.0.2', '10.0.0.3']
        slave_ips:  ['11.0.0.1', '11.0.0.2', '11.0.0.3']
  - name: source_slave
    run_list:
      # master recipe is only for asserting mesos-slave healthy startup.
      - recipe[mesos::master]
      - recipe[mesos::slave]
    attributes:
      mesos:
        type: source
        slave:
          master: localhost
        # these keys below are only for master configurations.
        master_ips: ['10.0.0.1', '10.0.0.2', '10.0.0.3']
        slave_ips:  ['11.0.0.1', '11.0.0.2', '11.0.0.3']
